ARDUINO_DIR            = /usr/share/arduino
TARGET                 = &lt;your project name&gt;
ARDUINO_LIBS           =
MCU                    = atmega328p
F_CPU                  = 16000000
ARDUINO_PORT           = &lt;serial port, e.g. /dev/ttyACM0&gt;
AVRDUDE_ARD_BAUDRATE   = 115200
AVRDUDE_ARD_PROGRAMMER = arduino

include mk/Arduino.mk
